jeeplus/src/main/java/com/jeeplus/modules/brokeruser/entity/BrokerUser.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.brokeruser.entity;

import com.jeeplus.modules.sys.entity.Office;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;

import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.excel.annotation.ExcelField;

/**
 * 经纪人管理Entity
 * @author 潘兴武
 * @version 2018-02-01
 */
public class BrokerUser extends DataEntity<BrokerUser> {
	
	private static final long serialVersionUID = 1L;
	private String companyId;		// 归属公寓
	private Office office;		// 归属部门
	private String loginName;		// 登录名（手机号）
	private String password;		// 密码
	private String no;		// 工号
	private String name;		// 姓名
	private String email;		// 邮箱
	private String phone;		// 电话
	private String mobile;		// 手机号码（登录用户名）
	private String userType;		// 用户类型：1经纪人
	private String photo;		// 用户头像
	private String loginIp;		// 最后登陆IP
	private Date loginDate;		// 最后登陆时间
	private String loginFlag;		// 是否可登录
	
	public BrokerUser() {
		super();
	}

	public BrokerUser(String id){
		super(id);
	}

	@ExcelField(title="归属公寓", align=2, sort=1)
	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}
	
	@ExcelField(title="归属部门", fieldType=Office.class, value="office.name", align=2, sort=2)
	public Office getOffice() {
		return office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}
	
	@ExcelField(title="登录名（手机号）", align=2, sort=3)
	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	
	@ExcelField(title="密码", align=2, sort=4)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@ExcelField(title="工号", align=2, sort=5)
	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}
	
	@ExcelField(title="姓名", align=2, sort=6)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@ExcelField(title="邮箱", align=2, sort=7)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@ExcelField(title="电话", align=2, sort=8)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	@ExcelField(title="手机号码（登录用户名）", align=2, sort=9)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	@ExcelField(title="用户类型：1经纪人", dictType="fq_user_tyepe", align=2, sort=10)
	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}
	
	@ExcelField(title="用户头像", align=2, sort=11)
	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}
	
	@ExcelField(title="最后登陆IP", align=2, sort=12)
	public String getLoginIp() {
		return loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}
	
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@ExcelField(title="最后登陆时间", align=2, sort=13)
	public Date getLoginDate() {
		return loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}
	
	@ExcelField(title="是否可登录", align=2, sort=14)
	public String getLoginFlag() {
		return loginFlag;
	}

	public void setLoginFlag(String loginFlag) {
		this.loginFlag = loginFlag;
	}
	
}

jeeplus/src/main/java/com/jeeplus/modules/echarts/entity/ChinaWeatherDataBean.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.echarts.entity;

import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;

import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.excel.annotation.ExcelField;

/**
 * 城市气温Entity
 * @author lgf
 * @version 2016-06-02
 */
public class ChinaWeatherDataBean extends DataEntity<ChinaWeatherDataBean> {
	
	private static final long serialVersionUID = 1L;
	private Date datestr;		// 日期
	private Double beijingMaxTemp;		// 北京最高气温
	private Double beijingMinTemp;		// 北京最低气温
	private Double changchunMaxTemp;		// 长春最高气温
	private Double changchunMinTemp;		// 长春最低气温
	private Double shenyangMaxTemp;		// 沈阳最高气温
	private Double shenyangMinTemp;		// 沈阳最低气温
	private Double haerbinMaxTemp;		// 哈尔滨最高气温
	private Double haerbinMinTemp;		// 哈尔滨最低气温
	
	public ChinaWeatherDataBean() {
		super();
	}

	public ChinaWeatherDataBean(String id){
		super(id);
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@ExcelField(title="日期", align=2, sort=7)
	public Date getDatestr() {
		return datestr;
	}

	public void setDatestr(Date datestr) {
		this.datestr = datestr;
	}
	
	@ExcelField(title="北京最高气温", align=2, sort=8)
	public Double getBeijingMaxTemp() {
		return beijingMaxTemp;
	}

	public void setBeijingMaxTemp(Double beijingMaxTemp) {
		this.beijingMaxTemp = beijingMaxTemp;
	}
	
	@ExcelField(title="北京最低气温", align=2, sort=9)
	public Double getBeijingMinTemp() {
		return beijingMinTemp;
	}

	public void setBeijingMinTemp(Double beijingMinTemp) {
		this.beijingMinTemp = beijingMinTemp;
	}
	
	@ExcelField(title="长春最高气温", align=2, sort=10)
	public Double getChangchunMaxTemp() {
		return changchunMaxTemp;
	}

	public void setChangchunMaxTemp(Double changchunMaxTemp) {
		this.changchunMaxTemp = changchunMaxTemp;
	}
	
	@ExcelField(title="长春最低气温", align=2, sort=11)
	public Double getChangchunMinTemp() {
		return changchunMinTemp;
	}

	public void setChangchunMinTemp(Double changchunMinTemp) {
		this.changchunMinTemp = changchunMinTemp;
	}
	
	@ExcelField(title="沈阳最高气温", align=2, sort=12)
	public Double getShenyangMaxTemp() {
		return shenyangMaxTemp;
	}

	public void setShenyangMaxTemp(Double shenyangMaxTemp) {
		this.shenyangMaxTemp = shenyangMaxTemp;
	}
	
	@ExcelField(title="沈阳最低气温", align=2, sort=13)
	public Double getShenyangMinTemp() {
		return shenyangMinTemp;
	}

	public void setShenyangMinTemp(Double shenyangMinTemp) {
		this.shenyangMinTemp = shenyangMinTemp;
	}
	
	@ExcelField(title="哈尔滨最高气温", align=2, sort=14)
	public Double getHaerbinMaxTemp() {
		return haerbinMaxTemp;
	}

	public void setHaerbinMaxTemp(Double haerbinMaxTemp) {
		this.haerbinMaxTemp = haerbinMaxTemp;
	}
	
	@ExcelField(title="哈尔滨最低气温", align=2, sort=15)
	public Double getHaerbinMinTemp() {
		return haerbinMinTemp;
	}

	public void setHaerbinMinTemp(Double haerbinMinTemp) {
		this.haerbinMinTemp = haerbinMinTemp;
	}
	
}

jeeplus/src/main/java/com/jeeplus/modules/echarts/entity/PieClass.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.echarts.entity;

import org.hibernate.validator.constraints.Length;

import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.excel.annotation.ExcelField;

/**
 * 班级Entity
 * @author lgf
 * @version 2016-05-26
 */
public class PieClass extends DataEntity<PieClass> {
	
	private static final long serialVersionUID = 1L;
	private String className;		// 班级
	private Integer num;		// 人数
	
	public PieClass() {
		super();
	}

	public PieClass(String id){
		super(id);
	}

	@Length(min=0, max=64, message="班级长度必须介于 0 和 64 之间")
	@ExcelField(title="班级", align=2, sort=7)
	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}
	
	@ExcelField(title="人数", align=2, sort=8)
	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}
	
}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/ChatHistory.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.iim.entity;

import org.hibernate.validator.constraints.Length;

import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.excel.annotation.ExcelField;

/**
 * 聊天记录Entity
 * @author jeeplus
 * @version 2015-12-29
 */
public class ChatHistory extends DataEntity<ChatHistory> {
	
	private static final long serialVersionUID = 1L;
	private String userid1;		// userid1 发送者id
	private String userid2;		// userid2 接收者id
	private String msg;		// msg
	private String status;		// status
	private String type;//聊天类型
	
	public ChatHistory() {
		super();
	}

	public ChatHistory(String id){
		super(id);
	}

	@Length(min=0, max=64, message="userid1长度必须介于 0 和 64 之间")
	@ExcelField(title="userid1", align=2, sort=1)
	public String getUserid1() {
		return userid1;
	}

	public void setUserid1(String userid1) {
		this.userid1 = userid1;
	}
	
	@Length(min=0, max=64, message="userid2长度必须介于 0 和 64 之间")
	@ExcelField(title="userid2", align=2, sort=2)
	public String getUserid2() {
		return userid2;
	}

	public void setUserid2(String userid2) {
		this.userid2 = userid2;
	}
	
	@Length(min=0, max=1024, message="msg长度必须介于 0 和 1024 之间")
	@ExcelField(title="msg", align=2, sort=3)
	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}
	
	@Length(min=0, max=45, message="status长度必须介于 0 和 45 之间")
	@ExcelField(title="status", align=2, sort=4)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}
	
}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/Friend.java
package com.jeeplus.modules.iim.entity;

/**
 * 好友
 * @author Swhite
 *
 */
public class Friend {
	
	private String id;//用户ID
	
	private String username;//用户名
	
	private String avatar; //头像
	
	private String sign; //签名
	
	private String remark;//备注
	
	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/FriendGroup.java
package com.jeeplus.modules.iim.entity;

import java.util.ArrayList;
import java.util.List;

/**
 * 好友列表
 * 
 * @author Swhite
 * 
 */
public class FriendGroup {
	private String groupname;// 好友分组名
	private int id; // 分组ID
	private int online; // 在线数量
	private List<Friend> list = new ArrayList<Friend>(); // 分组下的好友列表

	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public int getOnline() {
		return online;
	}

	public void setOnline(int online) {
		this.online = online;
	}

	public List<Friend> getList() {
		return list;
	}

	public void setList(List<Friend> list) {
		this.list = list;
	}

}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/LayFileJsonData.java
package com.jeeplus.modules.iim.entity;

public class LayFileJsonData {
	
	private String name;//文件存储的名字
	
	private String src;//文件存储的路径

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public String getSrc() {
		return src;
	}

}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/LayGroup.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.iim.entity;

import org.hibernate.validator.constraints.Length;
import java.util.List;
import com.google.common.collect.Lists;

import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.excel.annotation.ExcelField;

/**
 * 群组Entity
 * @author lgf
 * @version 2016-08-07
 */
public class LayGroup extends DataEntity<LayGroup> {
	
	private static final long serialVersionUID = 1L;
	private String groupname;		// 群组名
	private String avatar;		// 群头像
	private List<LayGroupUser> layGroupUserList = Lists.newArrayList();		// 子表列表
	
	public LayGroup() {
		super();
	}

	public LayGroup(String id){
		super(id);
	}

	@Length(min=0, max=64, message="群组名长度必须介于 0 和 64 之间")
	@ExcelField(title="群组名", align=2, sort=1)
	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
	
	@Length(min=0, max=256, message="群头像长度必须介于 0 和 256 之间")
	@ExcelField(title="群头像", align=2, sort=2)
	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
	
	public List<LayGroupUser> getLayGroupUserList() {
		return layGroupUserList;
	}

	public void setLayGroupUserList(List<LayGroupUser> layGroupUserList) {
		this.layGroupUserList = layGroupUserList;
	}
}

jeeplus/src/main/java/com/jeeplus/modules/iim/entity/LayGroupJsonData.java
package com.jeeplus.modules.iim.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * LayJson--->Data对象
 * 
 * @author Swhite
 * 
 */
public class LayGroupJsonData {
	
	private HashMap owner = new HashMap(); // 我的信息

	
	private List<Friend> list = new ArrayList(); // 群组中的成员列表


	public void setOwner(HashMap owner) {
		this.owner = owner;
	}


	public HashMap getOwner() {
		return owner;
	}


	public void setList(List<Friend> list) {
		this.list = list;
	}


	public List<Friend> getList() {
		return list;
	}


}

jeeplus/src/main/java/com/jeeplus/modules/oa/entity/OaNotify.java
/**
 * Copyright &copy; 2015-2020 <a href="http://www.jeeplus.org/">JeePlus</a> All rights reserved.
 */
package com.jeeplus.modules.oa.entity;

import java.util.List;

import org.hibernate.validator.constraints.Length;

import com.google.common.collect.Lists;
import com.jeeplus.common.persistence.DataEntity;
import com.jeeplus.common.utils.Collections3;
import com.jeeplus.common.utils.IdGen;
import com.jeeplus.common.utils.StringUtils;
import com.jeeplus.modules.sys.entity.User;

/**
 * 通知通告Entity
 * @author jeeplus
 * @version 2014-05-16
 */
public class OaNotify extends DataEntity<OaNotify> {
	
	private static final long serialVersionUID = 1L;
	private String type;		// 类型
	private String title;		// 标题
	private String content;		// 类型
	private String files;		// 附件
	private String status;		// 状态

	private String readNum;		// 已读
	private String unReadNum;	// 未读
	
	private boolean isSelf;		// 是否只查询自己的通知
	
	private String readFlag;	// 本人阅读状态
	
	private List<OaNotifyRecord> oaNotifyRecordList = Lists.newArrayList();
	
	public OaNotify() {
		super();
	}

	public OaNotify(String id){
		super(id);
	}

	@Length(min=0, max=200, message="标题长度必须介于 0 和 200 之间")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
	@Length(min=0, max=1, message="类型长度必须介于 0 和 1 之间")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Length(min=0, max=1, message="状态长度必须介于 0 和 1 之间")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Length(min=0, max=2000, message="附件长度必须介于 0 和 2000 之间")
	public String getFiles() {
		return files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getReadNum() {
		return readNum;
	}

	public void setReadNum(String readNum) {
		this.readNum = readNum;
	}

	public String getUnReadNum() {
		return unReadNum;
	}

	public void setUnReadNum(String unReadNum) {
		this.unReadNum = unReadNum;
	}
	
	public List<OaNotifyRecord> getOaNotifyRecordList() {
		return oaNotifyRecordList;
	}

	public void setOaNotifyRecordList(List<OaNotifyRecord> oaNotifyRecordList) {
		this.oaNotifyRecordList = oaNotifyRecordList;
	}
	
	/**
	 * 获取通知发送记录用户ID
	 * @return
	 */
	public String getOaNotifyRecordIds() {
		return Collections3.extractToString(oaNotifyRecordList, "user.id", ",") ;
	}
	
	/**
	 * 设置通知发送记录用户ID
	 * @return
	 */
	public void setOaNotifyRecordIds(String oaNotifyRecord) {
		this.oaNotifyRecordList = Lists.newArrayList();
		for (String id : StringUtils.split(oaNotifyRecord, ",")){
			OaNotifyRecord entity = new OaNotifyRecord();
			entity.setId(IdGen.uuid());
			entity.setOaNotify(this);
			entity.setUser(new User(id));
			entity.setReadFlag("0");
			this.oaNotifyRecordList.add(entity);
		}
	}

	/**
	 * 获取通知发送记录用户Name
	 * @return
	 */
	public String getOaNotifyRecordNames() {
		return Collections3.extractToString(oaNotifyRecordList, "user.name", ",") ;
	}
	
	/**
	 * 设置通知发送记录用户Name
	 * @return
	 */
	public void setOaNotifyRecordNames(String oaNotifyRecord) {
		// 什么也不做
	}

	public boolean isSelf() {
		return isSelf;
	}

	public void setSelf(boolean isSelf) {
		this.isSelf = isSelf;
	}

	public String getReadFlag() {
		return readFlag;
	}

	public void setReadFlag(String readFlag) {
		this.readFlag = readFlag;
	}
}

jeeplus/src/main/webapp/webpage/modules/oa/oaNotifyList.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/webpage/include/taglib.jsp"%>
<html>
<head>
	<title>通知管理</title>
	<meta name="decorator" content="default"/>
</head>
<body class="gray-bg">
<div class="wrapper wrapper-content">
<div class="ibox">
<div class="ibox-title">
		<h5>通知列表 </h5>
		<div class="ibox-tools">
			<a class="collapse-link">
				<i class="fa fa-chevron-up"></i>
			</a>
			<a class="dropdown-toggle" data-toggle="dropdown" href="form_basic.html#">
				<i class="fa fa-wrench"></i>
			</a>
			<ul class="dropdown-menu dropdown-user">
				<li><a href="#">选项1</a>
				</li>
				<li><a href="#">选项2</a>
				</li>
			</ul>
			<a class="close-link">
				<i class="fa fa-times"></i>
			</a>
		</div>
	</div>
    
    <div class="ibox-content">
	<sys:message content="${message}"/>
	
		<!-- 查询条件 -->
	<div class="row">
	<div class="col-sm-12">
		<form:form id="searchForm" modelAttribute="oaNotify" action="${ctx}/oa/oaNotify/${oaNotify.self?'self':''}" method="post" class="form-inline">
		<input id="pageNo" name="pageNo" type="hidden" value="${page.pageNo}"/>
		<input id="pageSize" name="pageSize" type="hidden" value="${page.pageSize}"/>
		<table:sortColumn id="orderBy" name="orderBy" value="${page.orderBy}" callback="sortOrRefresh();"/><!-- 支持排序 -->
		<div class="form-group">
			<span>标题：</span>
				<form:input path="title" htmlEscape="false" maxlength="200"  class=" form-control input-sm"/>
			
			<span>类型：</span>
				<form:select path="type"  class="form-control m-b">
					<form:option value="" label=""/>
					<form:options items="${fns:getDictList('oa_notify_type')}" itemLabel="label" itemValue="value" htmlEscape="false"/>
				</form:select>
			<c:if test="${!requestScope.oaNotify.self}"><span>状态：</span>
				<form:radiobuttons path="status" class="i-checks" items="${fns:getDictList('oa_notify_status')}" itemLabel="label" itemValue="value" htmlEscape="false"/>
			</c:if>
		
		 </div>	
	</form:form>
	<br/>
	</div>
	</div>
	
	
	<!-- 工具栏 -->
	<div class="row">
	<div class="col-sm-12">
		<div class="pull-left">
			<c:if test="${!requestScope.oaNotify.self}">
			<shiro:hasPermission name="oa:oaNotify:add">
				<table:addRow url="${ctx}/oa/oaNotify/form" title="通知"></table:addRow><!-- 增加按钮 -->
			</shiro:hasPermission>
			<shiro:hasPermission name="oa:oaNotify:edit">
			    <table:editRow url="${ctx}/oa/oaNotify/form" id="contentTable"  title="通知" width="800px" height="700px"></table:editRow><!-- 编辑按钮 -->
			</shiro:hasPermission>
			<shiro:hasPermission name="oa:oaNotify:del">
				<table:delRow url="${ctx}/oa/oaNotify/deleteAll" id="contentTable"></table:delRow><!-- 删除按钮 -->
			</shiro:hasPermission>
			<shiro:hasPermission name="oa:oaNotify:import">
				<table:importExcel url="${ctx}/oa/oaNotify/import"></table:importExcel><!-- 导入按钮 -->
			</shiro:hasPermission>
			<shiro:hasPermission name="oa:oaNotify:export">
	       		<table:exportExcel url="${ctx}/oa/oaNotify/export"></table:exportExcel><!-- 导出按钮 -->
	       </shiro:hasPermission>
	      
	       <button class="btn btn-white btn-sm " data-toggle="tooltip" data-placement="left" onclick="sortOrRefresh()" title="刷新"><i class="glyphicon glyphicon-repeat"></i> 刷新</button>
		 </c:if>
			</div>
		<div class="pull-right">
			<button  class="btn btn-primary btn-rounded btn-outline btn-sm " onclick="search()" ><i class="fa fa-search"></i> 查询</button>
			<button  class="btn btn-primary btn-rounded btn-outline btn-sm " onclick="reset()" ><i class="fa fa-refresh"></i> 重置</button>
		</div>
	</div>
	</div>
	
	
	
	
	<table id="contentTable" class="table table-striped table-bordered  table-hover table-condensed  dataTables-example dataTable no-footer">
		<thead>
			<tr>
				<th> <input type="checkbox" class="i-checks"></th>
				<th>标题</th>
				<th>类型</th>
				<th>状态</th>
				<th>查阅状态</th>
				<th>更新时间</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
		<c:forEach items="${page.list}" var="oaNotify">
			<tr>
				<td> <input type="checkbox" id="${oaNotify.id}" class="i-checks"></td>
				<td><a  href="#" onclick="openDialogView('查看通知', '${ctx}/oa/oaNotify/${requestScope.oaNotify.self?'view':'form'}?id=${oaNotify.id}','800px', '700px')">
					${fns:abbr(oaNotify.title,50)}
				</a></td>
				<td>
					${fns:getDictLabel(oaNotify.type, 'oa_notify_type', '')}
				</td>
				<td>
					${fns:getDictLabel(oaNotify.status, 'oa_notify_status', '')}
				</td>
				<td>
					<c:if test="${requestScope.oaNotify.self}">
						${fns:getDictLabel(oaNotify.readFlag, 'oa_notify_read', '')}
					</c:if>
					<c:if test="${!requestScope.oaNotify.self}">
						${oaNotify.readNum} / ${oaNotify.readNum + oaNotify.unReadNum}
					</c:if>
				</td>
				<td>
					<fmt:formatDate value="${oaNotify.updateDate}" pattern="yyyy-MM-dd HH:mm:ss"/>
				</td>
				<td>
				<c:if test="${!requestScope.oaNotify.self}">
					<shiro:hasPermission name="oa:oaNotify:view">
						<a href="#" onclick="openDialogView('查看通知', '${ctx}/oa/oaNotify/form?id=${oaNotify.id}','800px', '700px')" class="btn btn-info btn-xs btn-circle" ><i class="fa fa-search-plus"></i></a>
					</shiro:hasPermission>
					<shiro:hasPermission name="oa:oaNotify:edit">
    					<a href="#" onclick="openDialog('修改通知', '${ctx}/oa/oaNotify/form?id=${oaNotify.id}','800px', '700px')" class="btn btn-success btn-xs btn-circle" ><i class="fa fa-edit"></i></a>
    				</shiro:hasPermission>
    				<shiro:hasPermission name="oa:oaNotify:del">
						<a href="${ctx}/oa/oaNotify/delete?id=${oaNotify.id}" onclick="return confirmx('确认要删除该通知吗？', this.href)"   class="btn btn-danger btn-xs btn-circle"><i class="fa fa-trash"></i></a>
					</shiro:hasPermission>
				</c:if>
				</td>
			</tr>
		</c:forEach>
		</tbody>
	</table>
	<!-- 分页代码 -->
	<table:page page="${page}"></table:page>
	<br/>
	<br/>
	</div>
	</div>
</div>
</body>
</html>